version: "3.9"
services:
  listaweb:
    build: .
    ports:
      - "80:80"
    links: 
      -  mysqldb
  mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lista_Personas